# Generated by Django 5.2.5 on 2025-10-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_customuser_bio_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
