# Generated by Django 5.2.5 on 2025-10-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_file_article_media_type_delete_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('admin', 'Admin')], default='author', max_length=50),
        ),
    ]
